# Generated by Django 4.0.6 on 2022-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('suffix', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
