# Generated by Django 4.0.6 on 2022-08-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='suffix',
            field=models.CharField(blank=True, max_length=250, primary_key=True, serialize=False),
        ),
    ]
